= Levantamento de Requisitos - SISLEGIS

:numbered:
== Áreas interessadas

* Apoio Administrativo;
* Assessoria Parlamentar (ASPAR);
* Referência Legislativa;
* Gabinete de Assuntos Legislativo;

== Escopo da demanda
Criação de um novo sistema de acompanhamento legislativo, tendo em vista a demanda referente as Pautas Semanais com assuntos de interesse do Ministério da Justiça. Esse Sistema deverá organizar e facilitar o processo de manutenção das informações como Proposições, Dossiês, Exposição de Motivos, Manifestações, etc.



== Cenário Atual

Atualmente é utilizado pela SAL dois sistemas: EDENS e SISLegis(Desenvolvido pelo consultor Mateus). 

O Sistema Endens encontra-se em desuso pela Secretária, e o contrato com a empresa responsável pela manutenção foi cancelado.

Os motivos para não utilização do EDENS são:

* Grande número de funcionalidades desnecessárias;
* Interfaces complicadas;
* Problemas de integração com o MJDOC;
* Impossibilidade de anexação de arquivos;
* Problemas na verificação dos nomes dos Projetos de Leis importados, gerando duplicidade;
* Impossibilidade no acompanhamento de tarefas;
* Falta de funcionalidades importantes para a SAL;

O atual Sistema SisLegis também atende em partes os interesses da Secretária. Sua principal funcionalidade é a Pauta Semanal, porém ainda necessita de melhorias. Outro problema é o consumo das informações, pois somente é consumidas as informações da Câmara, faltando o "push" das informações do Senado.    

Em virtude da insuficiência dos dois Sistemas, é frequente entre as áreas: 

* Grande número de troca de e-mails; 
* Geração de planilhas em Excel para controle interno;
* Produção manual de documentos;
* Compartilhamento de arquivos na rede sem backup;


== Requisitos Funcionais




1.   *Manter Usuário*
a.   Anexar currículos da equipe;
b.   Gerenciar perfil usuário;

2.   *Consultar Tipo Proposição*

3.   *Manter Proposição*
a.   Incluir número do protocolo MJDOC;
b.   Consumir dados das duas casas legislativas;
c.   Acessar trâmites das proposições nas duas casas legislativas;
d.   Atrelar registro de manifestações e documentos administrativos relacionados;
e.   Anexar Dossiê;    
f.   Priorização das Proposições para reunião de Pauta;

4.   *Manter Exposições de Motivos*
-   Internas (de autoria do MJ)
a.   Elaborar EMI de acordo com as orientações do Manual de Redação da Presidência da República e geração de documento padronizados para impressão e assinatura;
b. Anexar notas elaboradas;
c. Anexar EMI’s arquivadas sobre o mesmo tema;
d. Relacionar a EMI com o PL e norma originada;

- Externo (de autoria de outros órgãos em co-autoria com o MJ)
a. Anexar texto das EMI's recebidas via SIDOF;
b. Juntar notas elaboradas;
c. Anexar documentos administrativos relacionados


5. *Manter Manifestação*
a. Notas;
b. Notas técnicas;
c. Pareceres;
d. Posicionamentos preliminares;
e. Anexar textos das manifestações
f. Gerar documento de Manifestação;

6. *Manter requerimento*
a. Criar alerta quando o prazo de Requerimento estiver próximo;

7. *Manter Contatos da Secretária*
a. Agendar compromissos;

8. *Cadastrar documentos administrativos*
a. Ofícios
b. Memorandos
c. Despachos

9. *Realizar controle de distribuição de demandas e prazos para resposta*
a. Anexar arquivos e notificações no módulo de tarefas
b. Filtro de destinatários
c. Notificação via e-mail
d. Priorização de tarefas
e. Possibilitar o usuário verificar suas tarefas

10. *Gerar relatórios referentes à distribuição das demandas, responsáveis e prazos*
a. Possibilidade de gerar em mais de um formato de arquivo

11. *Indexar temas por termos autorizados*

12. *Montar Pauta Semanal*
a. Consultar proposições das duas casas;

13. *Categorizar(tags) conteúdo*
a. Proposições;
b. Manifestações;

14. *Pesquisas por*
a. Forma livre, pesquisando todo conteúdo do portal;
b. Conteúdo dentro dos Documentos;
c. Categorias;

15. *Incluir dados do processo físico cadastrado no MJDOC*

16. *Migração de dados do EDENS para o sistema a ser construído*

17. *Manter demanda dos parlamentares*

18. *Manter parecer de sansão*

19. *Notificações de alterações de texto nos Projetos de Lei*

== Requisitos Funcionais da Referência (Humberto)
1. *Manter portarias*
2. *Pesquisa de portarias para o público externo*
3. *Migração de dados de portarias do sistema atual para o sistema a ser construído*

== Requisitos Funcionais da ASPAR
1. *Mecanismo de notificação automática a medida que requerimentos de interesse do MJ surjam nas pautas da Câmara ou do Senado*


== Requisitos Não Funcionais
1. *O Sistema será desenvolvido na linguagem Java;*
2. *O Sistema integra com outras aplicações;*
3. *O sistema deverá ser acessado completamente via browser;*

== Atores

* Chefe de Gabinete;
* Secretário de Assuntos Legislativos;
* Advogados;
* Coordenadores;
* Acessores;
* Equipe de apoio dos coordenadores;

== Glossário

[glossary]
EMI:: - Exposição de Motivos Interministerial.

PL:: - Projeto de Lei;

SAL:: - Secretária de Assunto Legislativo;

SIDOF:: - Sistema de Geração e Tramitação de Documentos

ASPAR:: - Assessoria Parlamentar




